### ISSUE TITLE
Unlisted Clips

### ISSUE THREAD

**Issue by ImVexed** [clipable/clipable#125]
It would be pretty useful for people to be able to upload clips without having them listed on the home page, and are only viewable via a direct link to the clip.

I think there's a few different things that would need to be done:
 - Unlisted boolean added to SQL model
 - Unlisted checkbox on upload clip page
 - SearchMany on clip db service needs to not include unlisted videos unless the person searching is the creator

**Comment by puckzxz** [comment]
@ImVexed I'll handle this one
