### ISSUE TITLE
Unable to register new account, with ALLOW_REGISTRATION set (using docker-compose)

### ISSUE THREAD

**Issue by Entheologian** [clipable/clipable#156]
I have used https://github.com/clipable/clipable/blob/master/docker-compose.yml with some changes seen below. 

> version: '2.1'
> 
> services:
>   postgres:
>     image: postgres:14
>     environment:
>       - POSTGRES_HOST_AUTH_METHOD=trust
>     volumes:
>       - pg_data:/var/lib/postgresql/data
>     healthcheck:
>       test: ["CMD-SHELL", "pg_isready -U postgres"]
>       interval: 1s
>       timeout: 5s
>       retries: 5
> 
>   minio:
>     image: minio/minio
>     volumes:
>       - minio_data:/data
>     # ports:
>     #   - 9001:9001
>     environment:
>       - "MINIO_ACCESS_KEY=minio"
>       - "MINIO_SECRET_KEY=myminiokeythatishouldchange123"
>     command: server /data --console-address ":9001"
> 
>   createbuckets:
>     image: minio/mc
>     depends_on:
>       - minio
>     entrypoint: >
>       /bin/sh -c "
>       /usr/bin/mc alias set clipable http://minio:9000 minio myminiokeythatishouldchange123;
>       /usr/bin/mc mb clipable/clips;
>       exit 0;
>       "
> 
>   clipable:
>     image: ghcr.io/clipable/clipable:latest
>     # All of these environment variables are documented here: https://github.com/clipable/clipable/wiki/Environment-Variables
>     environment:
>       MAX_UPLOAD_SIZE: 5GB
>       FFMPEG_CONCURRENCY: 1
>       FFMPEG_THREADS: 0
>       FFMPEG_PRESET: medium
>       FFMPEG_TUNE: film
>       DB_HOST: postgres
>       DB_PORT: 5432
>       DB_USER: postgres
>       DB_PASSWORD: postgres
>       DB_NAME: postgres
>       DB_IDHASHKEY: mydbidkeythatishouldchange123
>       COOKIE_KEY: mycookiekey12345
>       COOKIE_DOMAIN: docker.home.lan
>       ALLOW_REGISTRATION: "true"
>       #COOKIE_DOMAIN: localhost
>       #S3_BUCKET: clips
>       #S3_ACCESS: minio
>       #S3_SECRET: myminiokeythatishouldchange123
>       #S3_ADDRESS: minio:9000
>       #S3_SECURE: false
>     ports:
>       - 80:80
>     depends_on:
>       postgres:
>         condition: service_healthy
> 
> volumes:
>   pg_data: {}
>   minio_data: {}

If I use ALLOW_REGISTRATION: true (without quotes), I get this error:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.clipable.environment.ALLOW_REGISTRATION contains true, which is an invalid type, it should be a string, number, or a null
`
If I quote it, it's starts however I don't see a method to register/create new accounts. I see the login button under password and login at the top right hand corner, but no other buttons or links.

I have the same issue in that I cannot see how to add new accounts, using this config method as well:
"- ALLOW_REGISTRATION=true"

Did I change something incorrectly with this test config?

**Comment by ImVexed** [comment]
I can't replicate this issue you're having with `ALLOW_REGISTRATION contains true,` . If I set `ALLOW_REGISTRATION: true` I can `docker compose up` with no issues using your config.

You don't need to explicitly set it to true though, it is true by default. So just omitting the field should suffice. What is output for `docker compose version`? Maybe it's out of date?

Also, you'll need to uncomment all the `S3_` fields you commented out. The backend won't start without them.

**Comment by Entheologian** [comment]
I tried as you suggested, I un-commented the S3 lines and commented out the registration line and same issue.

I then removed these volumes, ie:
> docker volume ls |grep -i clip
> local     clipable_minio_data
> local     clipable_pg_data

* docker volume rm <vol. name>
* docker-compose down
* docker-compose system prune
* docker-compose image prune -a
* doas docker-compose up -d (re-pulled it)

Same issue... so then I built a new docker host, copied the docker-compose.yml to it, fired it up there and it works on that host, but still not this one.

The working docker host has this version (Debian Linux):
> $ doas docker-compose -v
> docker-compose version 1.25.0, build unknown

The problematic docker host has this version (Alpine Linux):
> $ doas docker-compose -v
> docker-compose version 1.29.2, build unknown

It's so bizarre but I am happy to see it working with the Debian docker host and I might just ditch Alpine after this issue. I don't know if it's related to the OS or not, but it's so bizarre with having identical docker-compose.yml files and both showing different results.

Thanks so much for the help, I will be switching this docker host to Debian after this so this issue can R.I.P.

**Comment by Entheologian** [comment]
I took it down since it also fixed another strange issue with docker, but I'll fire it up again hopefully this week, or weekend and take a look at the logs again to see.

**Comment by Entheologian** [comment]
I fired it up again and found the reason was due to a space in the "- MAX_UPLOAD_SIZE=" where as the new one I had cleaned up on setup which is why that one worked. lol. 

Thanks for your time and great project.

**Comment by ImVexed** [comment]
Cool! Glad it was an easy fix :)
