### ISSUE TITLE
Support MySQL JDBC

### ISSUE THREAD

**Issue by trashcluster** [clipable/clipable#157]
Hi,

Do you plan on supporting MySQL JDBC as well as Postgres ?

**Comment by ImVexed** [comment]
I'm not sure how we'd go about supporting multiple databases as our reverse ORM statically generates based off of our sql migration files, which currently use a lot of PSQL specific syntax.   

We'd have to have multiple migration folders for different database types or find a way to make our migrations agnostic to the database. Which seems like a whole heck of a lot of upfront work, on top of maintenance.   

Why do you want support for MySQL? I'm not sure I see the value in adding support for it.

**Comment by ImVexed** [comment]
Going to close this for now, but feel free to continue the discussion here.
