### ISSUE TITLE
GPU support no longer working

### ISSUE THREAD

**Issue by Cruv** [clipable/clipable#160]
As of today my GPU version of the docker container stopped working. It errors out during every encoding attempt even though my GPU drivers are successfully patched and recognized.

**Comment by ImVexed** [comment]
What error specifically are you getting? I'm unable to replicate this.

**Comment by Cruv** [comment]
I’ll have to pull logs for the exact error again but it definitely could be just docker being finicky with how it wants to list supported GPUs. The nvidia-smi command says it sees the 2060 and the driver hack works but it said something to the effect of “no supported devices” when it tried to start up ffmpeg to encode on the GPU. On Apr 21, 2023, at 1:30 PM, Cole ***@***.***> wrote:﻿
What error specifically are you getting? I'm unable to replicate this.

**Comment by Cruv** [comment]
@ImVexed here is what I get. 

Detected nvidia driver version: 525.105.17
Patch for this (525.105.17) nvidia driver not found.
Patch is available for versions: 
[and then it goes on to list the available versions]

I think maybe the driver hack that is deployed on the container startup is out of date since 525.105.17 is listed as supported over here:
https://github.com/keylase/nvidia-patch

**Comment by ImVexed** [comment]
I've merged in a fix in https://github.com/clipable/clipable/pull/161 to pull the patch script on container start instead of baking it into the image. Good catch. It should be available in ~30 minutes from the pipeline start.
