### ISSUE TITLE
Clipable Api

### ISSUE THREAD

**Issue by HametAk** [clipable/clipable#164]
Hello,

I'm trying to figure out how to access the api of clipable.
I want to upload videos via api or register a user, but I cant make it work.

Is there any documentation how to send the correct headers, data etc to the endpoint?
I'd appreciate it, thank you guys!

**Comment by ImVexed** [comment]
We don't have any swagger/openapi docs for our api, your best bet is just to check how the backend handles it, as the amount of routes is pretty small, and all of their status codes/logic is located in `routes/`. like https://github.com/clipable/clipable/blob/master/backend/routes/auth.go
and the frontend at
https://github.com/clipable/clipable/blob/master/frontend/src/shared/api.ts#L109

**Comment by HametAk** [comment]
Yes I figured that out, but I‘m a real noob in go. Is it possible to give me a basic cURL request how to upload a video file? I tried it for hours but no luck

**Comment by ImVexed** [comment]
```
❯ curl -v -X POST -b "webserver={...}; token={...}" -H "Content-Type: multipart/form-data"  -F "json={\"title\":\"asdasd\",\"description\":\"asdasd\",\"unlisted\":false}"  -F "video=@vid.mp4" http://localhost:8080/api/clips
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /api/clips HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Cookie: webserver={...}; token={...}
> Content-Length: 361877
> Content-Type: multipart/form-data; boundary=------------------------ba5ced2395049e8c
>
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Vary: Origin
< Date: Wed, 25 Oct 2023 04:42:45 GMT
< Content-Length: 233
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
{"id":"lMkL","title":"asdasd","description":"asdasd","created_at":"2023-10-24T21:42:45.973544-07:00","processing":true,"unlisted":false,"views":0,"creator":{"id":"LJxl","username":"asd","joined_at":"2023-10-24T21:31:34.48968-07:00"}}%
```
In general, you just need the cookies and then a multipart POST with the form field `json` containing the title and description, as well as a form field called `video` which is the video file
