### ISSUE TITLE
Register/login page support Enter key

### ISSUE THREAD

**Issue by ImVexed** [clipable/clipable#40]

**Comment by puckzxz** [comment]
Use an HTML form and the final button should be `type='submit'`

**Comment by AlexOla-NG** [comment]
Hi there @ImVexed @puckzxz 

If this hasn't been fixed, can you please assign it to me?

**Comment by AlexOla-NG** [comment]
Thanks for assigning me @ImVexed.

I've made the changes, I also fixed the label accessibility issue on the Register/Login pages. Please confirm if everything works on your end and merge PR🙏🏾

**Comment by ImVexed** [comment]
@AlexOla-NG I don't see a pull request if you made one.

**Comment by AlexOla-NG** [comment]
Hi @ImVexed, I had to quickly troubleshoot some git issues.

You should be able to see the PR now
